branches:
  only:
    - master

clone_depth: 50

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
    - GENERATOR: "Visual Studio 14 2015"

install:
  - cmake --version

  - git clone --depth=10 --quiet -- https://github.com/WeAreROLI/JUCE.git ../JUCE
  - cd ../JUCE
  - git reset --hard 75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - mkdir ci\build
  - cd ci\build

  - >
    cmake ..
    -G "%GENERATOR%"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/third-party/VST_SDK/VST3_SDK"
    -DJUCE_ROOT="../../../JUCE"
    -DJuceDemoPlugin_jucer_FILE="../../../JUCE/examples/audio plugin demo/JuceDemoPlugin.jucer"
    -DNetworkGraphicsDemo_jucer_FILE="../../../JUCE/examples/NetworkGraphicsDemo/NetworkGraphicsDemo.jucer"
    -DPlugin_Host_jucer_FILE="../../../JUCE/examples/audio plugin host/Plugin Host.jucer"
    -DProjucer_jucer_FILE="../../../JUCE/extras/Projucer/Projucer.jucer"

  - cmake --build . --config Debug
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%

  - >
    cmake
    -DJUCE_ROOT="../JUCE"
    -DJucer2Reprojucer_EXE="ci/build/Jucer2Reprojucer/Debug/Jucer2Reprojucer.exe"
    -P Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - git diff --quiet
