branches:
  only:
    - master

os: osx

install:
  - cmake --version

  - git clone --depth=1 --quiet -- https://github.com/WeAreROLI/JUCE.git ../JUCE

  - mkdir ~/SDKs
  - curl --location --output ~/SDKs/vstsdk3.zip http://www.steinberg.net/sdk_downloads/vstsdk367_03_03_2017_build_352.zip
  - unzip -q ~/SDKs/vstsdk3.zip -d ~/SDKs

script:
  - cmake -P cmake/test/run_all_tests.cmake

  - mkdir "examples/audio plugin host/build"
  - cd "examples/audio plugin host/build"
  - cmake .. -G Xcode
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd $TRAVIS_BUILD_DIR

  - mkdir examples/NetworkGraphicsDemo/build
  - cd examples/NetworkGraphicsDemo/build
  - cmake .. -G Xcode
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd $TRAVIS_BUILD_DIR

  - mkdir extras/Projucer/build
  - cd extras/Projucer/build
  - cmake .. -G Xcode
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd $TRAVIS_BUILD_DIR

  - mkdir "examples/audio plugin demo/build"
  - cd "examples/audio plugin demo/build"
  - cmake .. -G Xcode
  - cmake --build . --config Debug
  - cmake --build . --config Release
